### ISSUE TITLE
Invalid token size error

### ISSUE THREAD

**Issue by asib** [joekarl/go-libapns#14]
Just a suggestion, but I spent a while debugging an error where I was trying to send payloads that would force an Apple error response, and because I'm lazy I was trying to do this by using invalid tokens like `"abcd"`.

What I realised is that, because this is hex-decodable, the library is happy with it, but it causes an non-obvious bug. Given Apple expects tokens to be 32 bytes, sending a message with a token that's any other size will mean all the other fields are out of place. I ended up getting a `MISSING_PAYLOAD` for both valid and invalid tokens (due to framing - I was sending batches of notifications) and it took me a while to realise what the problem actually was.

So I was wondering whether it would be appropriate to introduce a token length check in `bufferPayload()` that returns an error if the non-decoded token is anything other than 64 bytes (this way we can avoid wasting time decoding it if it's an invalid length). It should go just before this line (https://github.com/joekarl/go-libapns/blob/20765710f428c92f4f3f6f4987d34020fb59ba03/connection.go#L346)

**Comment by joekarl** [comment]
This is a good check to have, will get a check in there.

**Comment by joekarl** [comment]
Merged
