### ISSUE TITLE
Allow custom socket

### ISSUE THREAD

**Issue by blixt** [joekarl/go-libapns#15]
Currently the function for creating an `APNSConnection` with a custom socket is private (used by the test). This functionality would be useful publicly for sandboxed environments where a different `net.Conn` implementation must be used (e.g., [App Engine's socket module](https://cloud.google.com/appengine/docs/go/sockets/reference)).

**Comment by joekarl** [comment]
Ah cool, I didn't even know they made you do that for app engine. 
I'll see what I can whip up.

**Comment by blixt** [comment]
This works for me: https://github.com/blixt/go-libapns/commit/d2ce7783bc8c65318137b9c5a5b0908140c30dd7

I realized after this commit that the `GatewayHost` value is still required for sandbox mode, as it's used for the TLS configuration.

**Comment by joekarl** [comment]
@blixt after some thinking, I basically just made the internal creation method public and added an extra method for constructing a valid config object. (see PR #15).
I don't know that there's really a right/wrong way here, but seems easier to not have to worry about a socket option in the config as that'd be a specialized use case.

Let me know what you think. Thanks for the input!

**Comment by blixt** [comment]
@joekarl This looks good to me. Just to confirm, would this be the recommended initialization?

```go
config := &APNSConfig{
    CertificateBytes: certPem,
    KeyBytes: keyPem,
}
apns.ApplyConfigDefaults(config)

conn := apns.SocketAPNSConnection(socket, config)
```

My only comment would be that it'd be nice if the only difference between `SocketAPNSConnection` and `NewAPNSConnection` would be the additional `net.Conn` parameter. So either apply config defaults in both functions, or leave it up to the user to do it before both functions. What do you think?

**Comment by joekarl** [comment]
Updated the PR to apply config validation directly on creating a `SocketAPNSConnection`.

Basically now you can pass in a raw tcp socket and a config. The `SocketAPNSConnection` will take in a raw socket and create the TLS client using it.

Should be able to do the following:
```go
config := &apns.APNSConfig{
    CertificateBytes: certPem,
    KeyBytes: keyPem,
}

conn, err := apns.APNSConnection(config)
```
or
```go
config := &apns.APNSConfig{
    CertificateBytes: certPem,
    KeyBytes: keyPem,
}

tcpSocket, err := net.DialTimeout("tcp",
	config.GatewayHost+":"+config.GatewayPort,
	time.Duration(config.SocketTimeout)*time.Second)
if err != nil {
	//failed to connect to gateway
	return nil, err
}

conn, err := apns.SocketAPNSConnection(tcpSocket, config)
```

**Comment by blixt** [comment]
@joekarl Nice! :+1:

**Comment by joekarl** [comment]
Cool! Will write up some README stuff and get that merged in.
Nice thing is it doesn't break backwards compatibility either.

**Comment by joekarl** [comment]
Merged
